export { default as React_icon} from '../images/react_icon.svg';
export { default as jquery_icon} from '../images/jquery_icon.svg';
export { default as mongodb_icon} from '../images/mongodb_icon.svg';
export { default as node_icon} from '../images/node_icon.svg';
export { default as javascript_icon} from '../images/javascript_icon.svg';
export { default as expressIcon } from '../images/express-icon.svg';
export { default as github} from '../images/github.svg';
export { default as medium} from '../images/medium.svg';
export { default as linkedin} from '../images/linkedin.svg';
export { default as email} from '../images/email.png';